In [5]:
# Start writing code here...
!pip install bs4
import pandas as pd
import requests
from bs4 import BeautifulSoup as soup

cricbuzz_url = requests.get("https://www.cricbuzz.com/cricket-stats/icc-rankings/men/batting")
cricbuzz_html = soup(cricbuzz_url.content,"html.parser")
player_rank = cricbuzz_html.findAll("div",{"class":"cb-col cb-col-16 cb-rank-tbl cb-font-16"})
player_name = cricbuzz_html.findAll("a",{"class":"text-hvr-underline text-bold cb-font-16"})
player_country = cricbuzz_html.findAll("div",{"class":"cb-font-12 text-gray"})
player_points = cricbuzz_html.findAll("div",{"class":"cb-col cb-col-17 cb-rank-tbl pull-right"})

test_rankings = {}
odi_rankings = {}
t20_rankings = {}



player_rankings_test = []
player_rankings_odi = []
player_rankings_t20 = []

player_name_test = []
player_name_odi= []
player_name_t20 = []


player_country_test= []
player_country_odi= []
player_country_t20= []

player_points_test = []
player_points_odi = []
player_points_t20 = []

for players in player_rank[:99]:
    player_rankings_test.append(players.text)
for players in player_rank[99:199]:
    player_rankings_odi.append(players.text)
for players in player_rank[199:299]:
    player_rankings_t20.append(players.text)

for players in player_name[:99]:
    player_name_test.append(players.text)
for players in player_name[99:199]:
    player_name_odi.append(players.text)
for players in player_name[199:299]:
    player_name_t20.append(players.text)

for players in player_country[:99]:
    player_country_test.append(players.text)
for players in player_country[99:199]:
    player_country_odi.append(players.text)
for players in player_country[199:299]:
    player_country_t20.append(players.text)

for players in player_points[:99]:
    player_points_test.append(players.text)
for players in player_points[99:199]:
    player_points_odi.append(players.text)
for players in player_points[199:299]:
    player_points_t20.append(players.text)

test_rankings['rank'] = player_rankings_test
test_rankings['name'] = player_name_test
test_rankings['country'] = player_country_test
test_rankings['points'] = player_points_test

odi_rankings['rank'] = player_rankings_odi
odi_rankings['name'] = player_name_odi
odi_rankings['country'] = player_country_odi
odi_rankings['points'] = player_points_odi

t20_rankings['rank'] = player_rankings_t20
t20_rankings['name'] = player_name_t20
t20_rankings['country'] = player_country_t20
t20_rankings['points'] = player_points_t20

Test = pd.DataFrame(test_rankings)
print(Test)
odi = pd.DataFrame(odi_rankings)
print(odi)
t20 = pd.DataFrame(t20_rankings)
t20

WARNING: The directory '/home/jovyan/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: bs4 in /opt/venv/lib/python3.7/site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in /opt/venv/lib/python3.7/site-packages (from bs4) (4.9.3)
Requirement already satisfied: soupsieve>1.2; python_version >= "3.0" in /opt/venv/lib/python3.7/site-packages (from beautifulsoup4->bs4) (2.1)
WARNING: You are using pip version 20.2.4; however, version 20.3.3 is available.
You should consider upgrading via the '/opt/venv/bin/python -m pip install --upgrade pip' command.
   rank                name       country points
0     1        Steven Smith     AUSTRALIA    911
1     2         Virat Kohli         INDIA    886
2     3     Kane Williamson   NEW ZEALAND    877
3     4  Marnus Labuschagne     AUSTRALIA    827
4     5          Babar Azam      PAKISTAN    797
..  ...                 ...           ...    ...
94   96   Lahiru Thirimanne     SRI LANKA    329
95   97        Javed Ahmadi   AFGHANISTAN    326
96   98       Marcus Harris     AUSTRALIA    323
97   99    Theunis de Bruyn  SOUTH AFRICA    317
98  100        George Linde  SOUTH AFRICA    311

[99 rows x 4 columns]
   rank                name      country points
0     1         Virat Kohli        INDIA    870
1     2        Rohit Sharma        INDIA    842
2     3          Babar Azam     PAKISTAN    837
3     4         Ross Taylor  NEW ZEALAND    818
4     5         Aaron Finch    AUSTRALIA    791
..  ...                 ...          ...    ...
95   96         Rashid Khan  AFGHANISTAN    402
96   97           Moeen Ali      ENGLAND    401
97   98      Kieron Pollard  WEST INDIES    397
98   99  Dimuth Karunaratne    SRI LANKA    390
99  100         Adil Rashid      ENGLAND    388

[100 rows x 4 columns]

   rank                   name       country points
0     1            Dawid Malan       ENGLAND    915
1     2             Babar Azam      PAKISTAN    871
2     3               KL Rahul         INDIA    816
3     4            Aaron Finch     AUSTRALIA    808
4     5  Rassie van der Dussen  SOUTH AFRICA    744
..  ...                    ...           ...    ...
92   96             Aqib Ilyas          OMAN    339
93   97        Shimron Hetmyer   WEST INDIES    339
94   98       Elton Chigumbura      ZIMBABWE    338
95   99            Gary Wilson       IRELAND    333
96  100        Nicholas Pooran   WEST INDIES    332

[97 rows x 4 columns]

In [ ]:
import pandas as pd